name: PocketClan
main: IchiKaku\PocketClan\PocketClan
version: 0.2-alpha
author: IchiKaku
api: [1.4.1]

commands:
 clan:
  usage: /clan [make/join/leave/list]
  permission: pocketclan.command
  description: true
 clanManage :
  usage: /clanManage [delete/ban/admin]
  permission: pocketclan.command
  description: true

permissions:
   pocketclan.command:
    default: true